### ISSUE TITLE
npm publish

### ISSUE THREAD

**Issue by dbashford** [ddlsmurf/mimosa-spritesmith#1]
Botched the initial commit a bit but got it where it should be.
- There was a bug with common directories that I addressed
- I removed the `placeholder` function as it won't be needed/used in `3.0`
- I addressed the `registerCommand` signature.
- fixed some lint errors
- moved the mimosa-config to js, mostly just copied the mimosa-sprite one as it stands now

Thanks for giving me rights! Made me try this out and it definitely shrinks the images over what mimosa-sprite was doing.  I don't have rights to publish though, so thats all you.

**Comment by ddlsmurf** [comment]
thats super cool, thanks a ton ! i think i also need to merge in ddlsmurf/mimosa-spritesmith-example somehow

**Comment by ddlsmurf** [comment]
would you have any suggestions about merging both repos ? I feel like most of the value of this module is for that specific configuration "example"

**Comment by dbashford** [comment]
Afraid you lost me.  The changes I made should have no effect on configuration of this module? I must be missing something sorry!

**Comment by ddlsmurf** [comment]
No there is little to no relation to this issue, its just a convenient way to contact you at this point. I just mean there is a separate repository ( ddlsmurf/mimosa-spritesmith-example  ) in which there is an example configuration that handles retina sprites in combination with this repository. I think they should probably be merged, but i'm not sure how or how much and seek your recommendation

**Comment by dbashford** [comment]
In the past I've done what you have done.  I've created a separate repo for examples.  Usually I just link out to it.  "Check here for an example"

**Comment by ddlsmurf** [comment]
(better late than never - again my gratitude for your work)
